name: Build and Deploy

on:
  push:
    branches:
      - github-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository 🛎️
        uses: actions/checkout@v4

      - name: Set up Python from `.python-version` 🐍
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies 📦
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Initialize Reflex 📦
        run: reflex init

      - name: Build the website 🚧
        run: |
          reflex export --no-zip --frontend-only
        env:
          API_URL: "http://www.boscoho.ca:8000"

      - name: Upload frontend build 📦
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: .web/_static/
          if-no-files-found: error
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the repository 🛎️
        uses: actions/checkout@v4

      - name: Download website build 📦
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: frontend/

      - name: GitHub Branch Deployer
        uses: nicholasgriffintn/github-branch-deployment-action@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: production
          FOLDER: frontend
          MESSAGE: 'Build: ({sha}) {msg}'
